name: Java CI with Maven

on:
  push:
    branches: [ 'thymeleaf3' ]
  pull_request:
    branches: [ 'thymeleaf3' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
        cache: maven
    - name: Build with Maven
      run: |
        mvn -B -U clean install -Dapp.log.level.test=info
        mvn -B jacoco:report -pl thymeleaf-extras-terasoluna-gfw

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: thymeleaf-extras-terasoluna-gfw/target/site/jacoco/jacoco.xml

    - name: action-maven-publish
      uses: samuelmeuli/action-maven-publish@v1.4.0
      if: ${{ matrix.java == '17' }}
      with:
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        maven_args: -Dmaven.test.skip=true -Dgpg.skip=false
